---
title: "WriteUp Linear Model with Prediction"
Author "Alfredo Acevedo"
Date "4/4/2024"
output: html_document
---
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

require(tidyverse)
require(tigerstats)
require(lubridate)
data <- read.csv(file="https://onlinestatbook.com/case_studies_rvls/physical_strength/data.txt",sep="",header=TRUE)
```

##model 1 SIMS~ARM

## scatter plot

```{r}
basicARM <- ggplot(data,aes(y=SIMS , x=ARM))
```

```{r}
basicARM + geom_point() + ggtitle ("SIMS VS ARM") + geom_smooth(method=lm)
```
```{r}
model.1 <- lm(SIMS~ARM, data=data)
```

```{r}
target<-data.frame(ARM=88, GRIP = 94)
```

```{r}
predict(model.1, target, interval=("prediction"))
```

## model 2 is SIMS-GRIP
##scatter plot


```{r}
basicGRIP <- ggplot(data,aes(y=SIMS , x=GRIP))
```

```{r}
basicGRIP + geom_point() + ggtitle ("SIMS VS GRIP") + geom_smooth(method=lm)
```

```{r}
model.2 <- lm(SIMS~GRIP, data=data)
```

```{r}
predict(model.2, target, interval=("prediction"))
```

##Model 3 SIMS-ARM-GRIP

```{r}
model.3 <- lm(SIMS~ARM+GRIP, data=data)
```

```{r}
predict(model.3, target, interval=("prediction"))
summary.lm(model.3)
```


```{r}
predict(model.3, target, interval=("confidence"))
```




